# Generated by Django 3.1.7 on 2021-03-19 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_company', models.TextField()),
                ('account_name', models.TextField()),
                ('account_number', models.TextField()),
                ('email', models.TextField()),
                ('is_demo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_no', models.TextField()),
                ('symbol', models.TextField()),
            ],
        ),
    ]
