# Generated by Django 3.1.7 on 2021-03-22 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_no', models.TextField()),
                ('symbol', models.TextField()),
                ('order_type', models.TextField(choices=[('0', 'Buy'), ('1', 'Sell')])),
            ],
        ),
    ]
